//import {Card, CardHeader, CardBody, CardFooter, Divider, Image} from "@nextui-org/react";
'use client'
import {Card, CardHeader, CardBody, CardFooter} from "@nextui-org/card";
import {Divider} from '@nextui-org/divider';
import {Image} from '@nextui-org/image';
import { Auth } from '@supabase/auth-ui-react'
import { ThemeSupa } from '@supabase/auth-ui-shared'
import { createClientComponentClient } from '@supabase/auth-helpers-nextjs'


//import { AuthComp } from "./auth-comp"

export default function AuthForm() {

  const supabase = createClientComponentClient()

  return (
    <Card className="max-w-[400px]">
      <CardHeader className="flex gap-3">
        <Image
          alt="ivy notes icon"
          width={40}
          height={40}
          radius="sm"
          src="/ivy-icon.png"
        />
        <div className="flex flex-col">
          <p className="text-md">Ivy Notes</p>
          <p className="text-small text-default-500"> Sustainable Note Taking</p>
        </div>
      </CardHeader>
      <Divider/>
      <CardBody>
        <Auth
        supabaseClient={supabase}
        view="magic_link"
        appearance={{ theme: ThemeSupa }}
        theme="dark"
        showLinks={false}
        providers={['google', 'facebook', 'twitter']}
        redirectTo="http://localhost:3000/auth/callback"
      />

      </CardBody>
      <Divider/>
      <CardFooter>
        <p>Ivy Notes is a note taking app focused on sustainability. A portion of revenue generated by the app is donated to environmental non-profits, so users can feel good knowing their note taking is helping support important causes to protect our planet.
</p>
      </CardFooter>
    </Card>

      )
}
